# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.request_round_register_data import RequestRoundRegisterData  # noqa: F401,E501
from swagger_server import util


class RequestRoundRegister(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, round_register_data: RequestRoundRegisterData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestRoundRegister - a model defined in Swagger

        :param round_register_data: The round_register_data of this RequestRoundRegister.  # noqa: E501
        :type round_register_data: RequestRoundRegisterData
        :param channel: The channel of this RequestRoundRegister.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestRoundRegister.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'round_register_data': RequestRoundRegisterData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'round_register_data': 'round_register_data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._round_register_data = round_register_data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestRoundRegister':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestRoundRegister of this RequestRoundRegister.  # noqa: E501
        :rtype: RequestRoundRegister
        """
        return util.deserialize_model(dikt, cls)

    @property
    def round_register_data(self) -> RequestRoundRegisterData:
        """Gets the round_register_data of this RequestRoundRegister.


        :return: The round_register_data of this RequestRoundRegister.
        :rtype: RequestRoundRegisterData
        """
        return self._round_register_data

    @round_register_data.setter
    def round_register_data(self, round_register_data: RequestRoundRegisterData):
        """Sets the round_register_data of this RequestRoundRegister.


        :param round_register_data: The round_register_data of this RequestRoundRegister.
        :type round_register_data: RequestRoundRegisterData
        """

        self._round_register_data = round_register_data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestRoundRegister.


        :return: The channel of this RequestRoundRegister.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestRoundRegister.


        :param channel: The channel of this RequestRoundRegister.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestRoundRegister.


        :return: The external_transaction_id of this RequestRoundRegister.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestRoundRegister.


        :param external_transaction_id: The external_transaction_id of this RequestRoundRegister.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
