# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestRoundRegisterData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: str=None, lat: str=None, long: str=None, out_round: bool=None, round_id: int=None, images: List[str]=None, observations: str=None):  # noqa: E501
        """RequestRoundRegisterData - a model defined in Swagger

        :param user: The user of this RequestRoundRegisterData.  # noqa: E501
        :type user: str
        :param lat: The lat of this RequestRoundRegisterData.  # noqa: E501
        :type lat: str
        :param long: The long of this RequestRoundRegisterData.  # noqa: E501
        :type long: str
        :param out_round: The out_round of this RequestRoundRegisterData.  # noqa: E501
        :type out_round: bool
        :param round_id: The round_id of this RequestRoundRegisterData.  # noqa: E501
        :type round_id: int
        :param images: The images of this RequestRoundRegisterData.  # noqa: E501
        :type images: List[str]
        :param observations: The observations of this RequestRoundRegisterData.  # noqa: E501
        :type observations: str
        """
        self.swagger_types = {
            'user': str,
            'lat': str,
            'long': str,
            'out_round': bool,
            'round_id': int,
            'images': List[str],
            'observations': str
        }

        self.attribute_map = {
            'user': 'user',
            'lat': 'lat',
            'long': 'long',
            'out_round': 'out_round',
            'round_id': 'round_id',
            'images': 'images',
            'observations': 'observations'
        }
        self._user = user
        self._lat = lat
        self._long = long
        self._out_round = out_round
        self._round_id = round_id
        self._images = images
        self._observations = observations

    @classmethod
    def from_dict(cls, dikt) -> 'RequestRoundRegisterData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestRoundRegisterData of this RequestRoundRegisterData.  # noqa: E501
        :rtype: RequestRoundRegisterData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this RequestRoundRegisterData.


        :return: The user of this RequestRoundRegisterData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this RequestRoundRegisterData.


        :param user: The user of this RequestRoundRegisterData.
        :type user: str
        """

        self._user = user

    @property
    def lat(self) -> str:
        """Gets the lat of this RequestRoundRegisterData.


        :return: The lat of this RequestRoundRegisterData.
        :rtype: str
        """
        return self._lat

    @lat.setter
    def lat(self, lat: str):
        """Sets the lat of this RequestRoundRegisterData.


        :param lat: The lat of this RequestRoundRegisterData.
        :type lat: str
        """

        self._lat = lat

    @property
    def long(self) -> str:
        """Gets the long of this RequestRoundRegisterData.


        :return: The long of this RequestRoundRegisterData.
        :rtype: str
        """
        return self._long

    @long.setter
    def long(self, long: str):
        """Sets the long of this RequestRoundRegisterData.


        :param long: The long of this RequestRoundRegisterData.
        :type long: str
        """

        self._long = long

    @property
    def out_round(self) -> bool:
        """Gets the out_round of this RequestRoundRegisterData.


        :return: The out_round of this RequestRoundRegisterData.
        :rtype: bool
        """
        return self._out_round

    @out_round.setter
    def out_round(self, out_round: bool):
        """Sets the out_round of this RequestRoundRegisterData.


        :param out_round: The out_round of this RequestRoundRegisterData.
        :type out_round: bool
        """

        self._out_round = out_round

    @property
    def round_id(self) -> int:
        """Gets the round_id of this RequestRoundRegisterData.


        :return: The round_id of this RequestRoundRegisterData.
        :rtype: int
        """
        return self._round_id

    @round_id.setter
    def round_id(self, round_id: int):
        """Sets the round_id of this RequestRoundRegisterData.


        :param round_id: The round_id of this RequestRoundRegisterData.
        :type round_id: int
        """

        self._round_id = round_id

    @property
    def images(self) -> List[str]:
        """Gets the images of this RequestRoundRegisterData.


        :return: The images of this RequestRoundRegisterData.
        :rtype: List[str]
        """
        return self._images

    @images.setter
    def images(self, images: List[str]):
        """Sets the images of this RequestRoundRegisterData.


        :param images: The images of this RequestRoundRegisterData.
        :type images: List[str]
        """

        self._images = images

    @property
    def observations(self) -> str:
        """Gets the observations of this RequestRoundRegisterData.


        :return: The observations of this RequestRoundRegisterData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this RequestRoundRegisterData.


        :param observations: The observations of this RequestRoundRegisterData.
        :type observations: str
        """

        self._observations = observations

    @classmethod
    def from_json(cls, data: Dict) -> "RequestRoundRegisterData":
        obj = cls()

        for attr, json_key in obj.attribute_map.items():
            if json_key in data:
                setattr(obj, attr, data[json_key])

        return obj
